# Travailler avec des vecteurs, des matrices et des tableaux dans NumPy

In [2]:
#Importer 
import numpy as np 

## INTRODUCTION 

NumPy est une bibliothèque python servant à manipuler les tableaux (Vecteurs, Matrices)

### Créer un vecteur

##### Le tableau multidimentionnel est la principale structure de données de NumPy, Les vecteurs sont des tableaux undimentionnels ==> Horizontaux ou verticaux 

In [3]:
#vecteur ligne 
vector_row = np.array([1,2,3])
print(vector_row)
#vecteur colonne
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


[Tutoriel sur les vecteurs](https://www.mathsisfun.com/algebra/vectors.html)


[Vecteur euclidien](https://fr.wikipedia.org/wiki/Vecteur_euclidien)

### Créer une matrice 

In [30]:
#Matrice normale
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


### Créer une matrice creuse
Une  matrice creuse permet de compresser les matrices avec beaucoup de zéros. 

Exemple Netflix !

In [31]:
from scipy import sparse
matrix_ = np.array([[0,0],
                    [0,1],
                    [3,0]])
# créer une matrice creuse
matrix_sparse = sparse.csr_matrix(matrix_)
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [32]:
#Nouvelle matrice creuse
matrix_3_6 = np.array([[0,0,0,0,0,0],
                       [0,0,0,0,1,0],
                       [3,0,0,0,0,0]])
matrix_sparse_3_6 = sparse.csr_matrix(matrix_3_6)
print(matrix_sparse_3_6)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 6)>
  Coords	Values
  (1, 4)	1
  (2, 0)	3


### Préallouer des tableaux NumPy
Créer une matrice rempli de 0 ou de 1 ou de n'importe quel nombre

In [36]:
vecteur_0 = np.zeros(shape=(3,1))
print(vecteur_0)
vecteur_1 = np.ones(shape=(3,1))
print(vecteur_1)
vect = np.full((3,1),100)
print(vect)

[[0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]]
[[100]
 [100]
 [100]]


### Sélectionner des éléments
###### Pour les index, le 1er élément porte l'index 0 et ainsi de suite...

In [37]:
#créer un vecteur ligne 
vector = np.array([1,2,3,4,5,6])
#Créer une matrice
matrix_5 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(vector[2])
print(matrix_5[1,1])

3
5


In [38]:
# Sélectionner tous les éléments d'un vecteur
print(vector[ :])
# Sélectionner la totalité jusqu'au 3e élément inclu
print(vector[ :3])
# Sélectionner tous ce qui est le 3e élément 
print(vector[3 :])
# Sélectionner le dernier élément
print(vector[-1])
# Inversion du vecteur
print(vector[ ::-1])

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[6 5 4 3 2 1]


In [39]:
# Sélectionner les 2 premières lignes et toutes les colonnes d'une matrice 
print(matrix_5[:2, :])
# Sélectionner toutes les lignes et la 2e colonne
print(matrix_5[ :, 1:2])

[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


### Décrire une matrice 
###### Trouver la forme, la taile et la dimension d'une matrice 

In [40]:
#Création d'une matrice 
matrix_6 = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]])

#Nombre de ligne et de colonnes 
print(matrix_6.shape)
#Nombre d'éléments
print(matrix_6.size)
#Nombre de dimension 
print(matrix_6.ndim)

(3, 4)
12
2


### Appliquer des fonctions à chaque élément 

In [19]:
# Créer une fonction qui ajoute 3462 à qqch 
add_3462 = lambda i : i + 3462 
# Créer une fonction vectorisée
vectorized_add_3462 = np.vectorize(add_3462)
#Application de la fonction à tous les éléments de la matrice
vectorized_add_3462(matrix_5)

array([[3463, 3464, 3465],
       [3466, 3467, 3468],
       [3469, 3470, 3471]])

In [20]:
# On aurais pu simplement faire 
matrix_5 + 3462

array([[3463, 3464, 3465],
       [3466, 3467, 3468],
       [3469, 3470, 3471]])

### Rechercher les valeurs maximales et minimales 

In [21]:
#Maximum 
print(np.max(matrix_5))
#Minimale
print(np.min(matrix_5))

9
1


In [22]:
#Maximum de chaque colonne
print(np.max(matrix_5, axis=0))
#Minimum de chaque ligne 
print(np.max(matrix_5, axis=1))

[7 8 9]
[3 6 9]


### Calculer la moyenne, la variance et l'écart-type

In [23]:
#La moyenne 
print(np.mean(matrix_5))
#La variance 
print(np.var(matrix_5))
#L'écart-type
print(np.std(matrix_5))

5.0
6.666666666666667
2.581988897471611


###### On peut aussi le faire un seul axe 

In [24]:
print(np.mean(matrix_5, axis=0))

[4. 5. 6.]


### Modifier la forme d'un tableau

In [ ]:
# Matrice 4*3
print(matrix_6)
# tranformée en matrice 2*6
print(matrix_6.reshape(2,6))
# reshape(1,-1) transforme en vecteur ligne
print(matrix_6.reshape(1,-1))
# reshape(-1,1) transforme en vecteur colonne
print(matrix_6.reshape(-1,1))
# reshape avec un nombre supérieur au nombre d'éléments renvoie une erreur

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


#### Transposé un vecteur ou matrice 
les vecteurs ne sont pas transposable 

In [47]:
# Transposer une matrice
print(matrix_6.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Inversion de vecteur : On utilise un double crochets 

In [49]:
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### Aplatir une matrice 

In [ ]:
# Créer une matrice 3*5 
matrix_7 = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15]])
# Aplatir avec ravel
print(matrix_7.ravel())
# Aplatir avec flatten
print(matrix_7.flatten())
# Aplatir avec reshape
print(matrix_7.reshape(1,-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### Le rang d'une matrice
Le rang d'une matrice est la dimension de l'espace vectoriel couvert par ses colonnes et ses lignes

In [52]:
np.linalg.matrix_rank(matrix_7)

np.int64(2)

#### La diagonale d'une matrice 

In [56]:
print(matrix_5)
#la diagonale principale
print(matrix_5.diagonal())
#la diagonale au dessus de la diagonale principale
print(matrix_5.diagonal(offset=1))
#la diagonale en dessous de la diagonale principale
print(matrix_5.diagonal(offset=-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[2 6]
[4 8]
