les 3 façon d'importer Numpy

In [1]:
#import numpy 
import numpy as np 

np.array() ==> Conception de matrice 

In [2]:
#conception de tableau avec une ligne 
A = np.array([[1,2,3]]) 
print(A)

[[1 2 3]]


In [3]:
#conception de vecteur
B = np.array([1,2,3])
print(B)

[1 2 3]


In [4]:
#conception de tableau de colonnes 
C = np.array([[1],[2],[3]])
print(C)

[[1]
 [2]
 [3]]


In [5]:
#conception de tableau avec des colonnes et des lignes 
D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#afficher exponentiel (e) et pi (π)
e = np.e
pi = np.pi
print("e =",e, "/π =",pi) 

e = 2.718281828459045 /π = 3.141592653589793


les matrices np.one(), np.zeros() et np.eye()

In [7]:
U1 = np.ones(5) #Cela nous renvoie un vecteur composer de chiffre 1 (float) 
print(U1)

[1. 1. 1. 1. 1.]


In [8]:
#il est possible de créer une matrice de 1, il faut ajouter le nbre de ligne et de colonnes entre parenthèse
#on a donc une double parenthèse 
U2 = np.ones((3,4))
print(U2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#pareil pour np.zeros(), elle renvoie une matrice de 0 
O1 = np.zeros(3)
print(O1)

[0. 0. 0.]


In [10]:
O2 = np.zeros((4,5))
print(O2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#cela permet de générer une matrice identitaire
I1 = np.eye(2,2)
print(I1)

[[1. 0.]
 [0. 1.]]


In [12]:
#il est possible de générer une matrice identitaire non carré 
I2 = np.eye(2,4)
print(I2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


Extraction et modification de données dans une matrice 

In [13]:
#On donne la matrice C suivante
C = np.array([[1,3,4,3],[7,6,5,2],[1,4,8,3]])
print(C)

[[1 3 4 3]
 [7 6 5 2]
 [1 4 8 3]]


In [14]:
print(C[0,0])
print(C[:,2])
print(C[2,:])

1
[4 5 8]
[1 4 8 3]


In [15]:
#Pour modifier une colonnes, on se sert de cette notation
print(C[:,[2]])

[[4]
 [5]
 [8]]


In [16]:
#Exemple :
N = np.array([[10],[20],[30]])
print(N)

[[10]
 [20]
 [30]]


In [17]:
C[:,[2]] = N
print(C) # Eh voila on a bien remplacé la 3e colonne (index = 2) par la matrice N 

[[ 1  3 10  3]
 [ 7  6 20  2]
 [ 1  4 30  3]]


In [18]:
C[0,3] = 17
print(C)

[[ 1  3 10 17]
 [ 7  6 20  2]
 [ 1  4 30  3]]


In [19]:
#Extraire une sous-matrice 
print(C[1:3,1:3])
print("---------------")
print(C[1:3,2:4])
print("---------------")
print(C[:,:]) # Cela renvoie toutes la matrice. 
                #les deux points (:) permet de sélectionner toute une ligne ou une colonnes 

[[ 6 20]
 [ 4 30]]
---------------
[[20  2]
 [30  3]]
---------------
[[ 1  3 10 17]
 [ 7  6 20  2]
 [ 1  4 30  3]]


Exercice :

a) Créer une matrice Z à l'aide de la commande np.ones() et de boucle "for" et l'afficher

In [20]:
#On donne la matrice suivante: 
Z = np.array([[1,1,1,1,1],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,1,1,1,1]])
print(Z)
# Ne pas oublier les doubles crochets dans l'utilisation de 'array()' 

[[1 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 1 1]]


In [21]:
# !!! Attention : il ne faut pas oublier que le dernier index n'est pas pris en compte 
# [n;m[ intervalle fermé en 'n' et ouvert en 'm' 
Z1 = np.ones((5,5))
for i in range(1,4):
    for j in range(1,5):
        Z1[i,j] = 0

print(Z1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


b) Créer la matrice Z à l'aide de np.zeros(), de boucle for et l'afficher  

In [22]:
Z2 = np.zeros((5,5))
print(Z2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# [i,j] \ i ==> colonnes et j ==> lignes

for j in range(0,5):
    Z2[0,j] = 1
    Z2[4,j] = 1
for i in range(0,5):
    Z2[i,0] = 1

print(Z2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


c) Créer la matrice Z à l'aide de np.ones et d'une modification de np.zeros puis afficher 

In [24]:
Z3 = np.ones((5,5))
print(Z3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
Z3[1:4,1:5] = np.zeros((3,4))
print(Z3)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [26]:
#Essayons avec np.zeros
Z4 = np.zeros((5,5))
print(Z4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
Z4[0,1:5] = 1
Z4[4,1:5] = 1
for i in range(0,5):
    Z4[i,0] = 1

print(Z4)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


np.arange(D,O,P) ==> créer un vecteur ligne sur l'intervalle ouvert [a,b[ avec un pas  de 'p'

In [28]:
#DOP ==> Départ, Obstacle(fin), Pas
W = np.arange(-2,16,4) # a et b peuvent être des réels (float)
print(W)
W1 = np.arange(0.5,14.2) #Par défaut le pas est 1 
print(W1)
W2 = np.arange(10,0,-1) #le pas peut être négatif 
# !!! Attention : si le pas est négatif, il faut commencer pas le plus grand pour aller vers le plus petit 
print(W2)

[-2  2  6 10 14]
[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5]
[10  9  8  7  6  5  4  3  2  1]


np.linspace(D,A,Nte) ==> créer un vecteur ligne

In [29]:
#DANte ==> Départ, Arrivée, Nbre de terme 
R = np.linspace(0,10,2)
print(R)
# Reprenons la même chose avec 5 terme 
R1 = np.linspace(0,10,5)
print(R1)

[ 0. 10.]
[ 0.   2.5  5.   7.5 10. ]


Opérations avec les matrices

In [30]:
#Opérations coefficients par coefficients 
print(D+1) # Addition d'une matrice avec un scalaire
print("________________________")
print("------------------------")
B = 10 * np.ones((3,3)) # Multiplication d'une matrice avec un scalaire 
print(B)
print("________________________")
print("------------------------")
print(D+B) # Addition de deux matrices 
print("________________________")
print("------------------------")
print(D-B) # Soustraction de deux matrices
print("________________________")
print("------------------------")
print(D*B) # Multiplication de deux matrices
print("________________________")
print("------------------------")
print(D/B) # Division de deux matrices 
print("________________________")
print("------------------------")
print(D**B) # Exposant de matrice par une autre matrice



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
________________________
------------------------
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
________________________
------------------------
[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]
________________________
------------------------
[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]
________________________
------------------------
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
________________________
------------------------
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
________________________
------------------------
[[1.00000000e+00 1.02400000e+03 5.90490000e+04]
 [1.04857600e+06 9.76562500e+06 6.04661760e+07]
 [2.82475249e+08 1.07374182e+09 3.48678440e+09]]


Exercice : 
            Utiliser np.ones et np.eye pour créer une matrice 

In [31]:
#On donne le matrice 

M = (np.array([[-8,4,4],[4,-8,4],[4,4,-8]]))/1 #J'ai divisé par un 1 pour avoir des floats 
print(M)

#Recréer la matrice M

print("________________________")
print("------------------------")

M2 = 4 * np.ones((3,3)) - 12 * np.eye(3,3)
print(M2)

[[-8.  4.  4.]
 [ 4. -8.  4.]
 [ 4.  4. -8.]]
________________________
------------------------
[[-8.  4.  4.]
 [ 4. -8.  4.]
 [ 4.  4. -8.]]


Produit de matrices 

In [32]:
#on donne les matrices A et B 
A = np.array([[11,24,36],[73,53,19],[42,34,45]])
print(A)
print("________________________")
print("------------------------")
print(B)
# Le produit de A et de B est PR
PR = np.dot(A,B)
print("________________________")
print("------------------------")
print("le produit de A et de B est :")
print(PR)


[[11 24 36]
 [73 53 19]
 [42 34 45]]
________________________
------------------------
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
________________________
------------------------
le produit de A et de B est :
[[ 710.  710.  710.]
 [1450. 1450. 1450.]
 [1210. 1210. 1210.]]


In [33]:
#le produit de trois matrices 
PR1 = np.dot(A,np.dot(B,D))
print(PR1)

# Pour le produit de trois matrices, il faut soit utiliser 2 fois np.dot() ou
# on peut affecter le 1er produit à une variable puis après multiplier par la troisième matrice
# !!! Attention : Ne pas oublier la règle du produit d'une matrice [(n,m) * (m,p) = (n,p)]

[[ 8520. 10650. 12780.]
 [17400. 21750. 26100.]
 [14520. 18150. 21780.]]


Inverse de matrice 

In [34]:
# A**(-1) renvoie l'inverse de chaque coefficients
# Pour calculer l'inverse d'une matrice, on utilise les fonctions : 
# np.linalg.inv() ou al.inv() , np.linalg.matrix_power(matrice, -1) 
#np.linalg.matrix_power() sert au fait à calculer les puissances de matrices
# !!! Attention : la matrice doit être inversible [ |D| ≠ 0 ] 
# Pour utiliser al.inv(), il faut importer le module numpy.linalg 

A_inv = np.linalg.inv(A)
print(A_inv)
print("________________________")
print("------------------------")
A_inv2 = np.linalg.matrix_power(A,-1)
print(A_inv2)

print("________________________")
print("------------------------")
#Verifions que A_inv est bien l'inverse de A 
 
Vérifions = np.dot(A,A_inv)
print(Vérifions)
# On obtient bien la matrice identité avec des 1 sur la diagonales principales 
# et des nombres proches de 0  


[[-0.05548288 -0.00459433  0.04632613]
 [ 0.07934786  0.03244744 -0.07717832]
 [-0.00816769 -0.0202278   0.037297  ]]
________________________
------------------------
[[-0.05548288 -0.00459433  0.04632613]
 [ 0.07934786  0.03244744 -0.07717832]
 [-0.00816769 -0.0202278   0.037297  ]]
________________________
------------------------
[[ 1.00000000e+00  4.16333634e-17 -2.49800181e-16]
 [-5.62050406e-16  1.00000000e+00 -1.31838984e-16]
 [-5.20417043e-16 -3.12250226e-17  1.00000000e+00]]


Transposé de matrice 

In [35]:
# On utilise la fonction np.transpose() ou Matrice.transpose()
# la transposé est impossible avec cette fonction 
# Pour rappel les vecteurs se note : np.array([x,y,z]) avec une seule paire de crochets 
# Exemple :
Vecteur = np.array([1,2,3])
vecteur_transpose = np.transpose(Vecteur)
print(vecteur_transpose) # rien ne se passe !!!

print("________________________")
print("------------------------")
# Essayons maintenant avec une matrice 
print(N)
print("________________________")
print("------------------------")
N_transpose = np.transpose(N)
print(N_transpose)

print("________________________")
print("------------------------")
N_transpose = N.transpose()
print(N_transpose)


[1 2 3]
________________________
------------------------
[[10]
 [20]
 [30]]
________________________
------------------------
[[10 20 30]]
________________________
------------------------
[[10 20 30]]


la fonction np.shape()

In [36]:
Shape = np.shape(A)
print(Shape)

(3, 3)


In [57]:
# a : nbre de lignes et b : nbre de colonnes 
a,b = np.shape(A)
print("a =",a)
print("------------------------")
print("b =",b)

a = 3
------------------------
b = 3


np.min(), np.max(), np.mean(),np.median, np.var(), np.std() 

In [40]:
# On donne la matrice A 
print(A)

[[11 24 36]
 [73 53 19]
 [42 34 45]]


In [41]:
print("le minimun des coefficients est ", np.min(A))
print("le maximum des coefficients est ", np.max(A))
print("la moyenne des coefficients est ", np.mean(A))
print("la médiane des coefficients est ", np.median(A))
print("la variance des coefficients est ", np.var(A))
print("l'écart-type des coefficients est ", np.std(A))

le minimun des coefficients est  11
le maximum des coefficients est  73
la moyenne des coefficients est  37.44444444444444
la médiane des coefficients est  36.0
la variance des coefficients est  313.13580246913574
l'écart-type des coefficients est  17.695643601438626


In [45]:
# La fonction np.min(A,0) renvoie un vecteur dont les composantes sont les minimum de chaque colonne
# et np.min(A,1) renvoie un vecteur dont les composantes sont les minimum de chaque ligne

print("le minimum de chaque colonnes est :", np.min(A,0))
print("le minimum de chaque ligne est :", np.min(A,1))

print("________________________")
print("------------------------")

# Idem avec avec la fonction np.max()
print("le maximum de chaque colonnes est :", np.max(A,0))
print("le maximum de chaque ligne est :", np.max(A,1))



le minimum de chaque colonnes est : [11 24 19]
le minimum de chaque ligne est : [11 19 34]
________________________
------------------------
le maximum de chaque colonnes est : [73 53 45]
le maximum de chaque ligne est : [36 73 45]


In [51]:
# Pareil avec np.mean(), np.median(), np.var(), np.std()
print("la moyenne de chaque colonne est :", np.mean(A,0))
print("la moyenne de chaque ligne est :", np.mean(A,1))
print("________________________")
print("------------------------")
print("le médiane de chaque colonne est :", np.median(A,0))
print("le médiane de chaque ligne est :", np.median(A,1))
print("________________________")
print("------------------------")
print("la variance de chaque colonne est :", np.var(A,0))
print("la variance de chaque ligne est :", np.var(A,1))
print("________________________")
print("------------------------")
print("l'écart-type de chaque colonnes est :", np.std(A,0))
print("l'écart-type de chaque ligne est :", np.std(A,1))


la moyenne de chaque colonne est : [42.         37.         33.33333333]
la moyenne de chaque ligne est : [23.66666667 48.33333333 40.33333333]
________________________
------------------------
le médiane de chaque colonne est : [42. 34. 36.]
le médiane de chaque ligne est : [24. 53. 42.]
________________________
------------------------
la variance de chaque colonne est : [640.66666667 144.66666667 116.22222222]
la variance de chaque ligne est : [104.22222222 496.88888889  21.55555556]
________________________
------------------------
l'écart-type de chaque colonnes est : [25.31139401 12.0277457  10.78064109]
l'écart-type de chaque ligne est : [10.20892855 22.29100466  4.64279609]


np.sum() et np.prod()

In [56]:
# les fonctions np.sum() et np.prod() permettent de faire la somme 
# et le produit des coefficients d'une matrice

print("la somme des coefficients de A est : ", np.sum(A))
print("le produit des coefficients de A est : ", np.prod(A))

print("________________________")
print("------------------------")

# il est aussi possible de le faire sur les colonne ou sur les lignes
print("la somme des coefficients des colonnes de A est : ", np.sum(A,0))
print("la somme des coefficients des lignes de A est : ", np.sum(A,1))

print("________________________")
print("------------------------")

print("le produit des coefficients des colonnes de A est : ", np.prod(A,0))
print("le produit des coefficients des lignes de A est : ", np.prod(A,1))

la somme des coefficients de A est :  337
le produit des coefficients de A est :  44895155437440
________________________
------------------------
la somme des coefficients des colonnes de A est :  [126 111 100]
la somme des coefficients des lignes de A est :  [ 71 145 121]
________________________
------------------------
le produit des coefficients des colonnes de A est :  [33726 43248 30780]
le produit des coefficients des lignes de A est :  [ 9504 73511 64260]


np.cumsum(), np.cumprod()

In [66]:
# la fonction np.cumsum() permet de faire la somme cumulative
# la fonction np.cumprod() permet de faire le produit cumulative
print("la somme cumulative des coefficients de A est : ", np.cumsum(A))
print("la somme cumulative des coefficients des colonnes de A est : ")
print(np.cumsum(A,0))
print("la somme cumulative des coefficients des lignes de A est : ")
print(np.cumsum(A,1))
print("________________________")
print("------------------------")
print("le produit cumulative des coefficients de A est : ")
print(np.cumprod(A))
print("le produit cumulative des coefficients des colonnes de A est : ")
print( np.cumprod(A,0))
print("le produit cumulative des coefficients des lignes de A est : ")
print( np.cumprod(A,1))

la somme cumulative des coefficients de A est :  [ 11  35  71 144 197 216 258 292 337]
la somme cumulative des coefficients des colonnes de A est : 
[[ 11  24  36]
 [ 84  77  55]
 [126 111 100]]
la somme cumulative des coefficients des lignes de A est : 
[[ 11  35  71]
 [ 73 126 145]
 [ 42  76 121]]
________________________
------------------------
le produit cumulative des coefficients de A est : 
[            11            264           9504         693792
       36770976      698648544    29343238848   997670120832
 44895155437440]
le produit cumulative des coefficients des colonnes de A est : 
[[   11    24    36]
 [  803  1272   684]
 [33726 43248 30780]]
le produit cumulative des coefficients des lignes de A est : 
[[   11   264  9504]
 [   73  3869 73511]
 [   42  1428 64260]]
